---
title: "Teaching, 2023/2024"
subtitle: "Data analysis and visualization for journalists"
theme: "jekyll-theme-minimal"
layout: default
---

<head>

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">


<style>
#toc_container {
    background: transparent; /* Set the background to transparent */
    border: none;
    padding: 10px; /* Add padding to create space between content and box */
    max-width: 400px; /* Set a maximum width for the container */
    margin: 50px auto; /* Center the container horizontally using margin: 0 auto; */
    text-align: center;
}

.toc_title {
    font-size: 18px;
    font-weight: 700;
    text-align: center;
}

#toc_container li, #toc_container ul, #toc_container ul li{
    list-style: outside none none !important;
    font-size: 16px;        
}

#toc_container a {
    color: #000;
}
</style>

</head>


&nbsp; <br>
&nbsp; <br>
&nbsp; <br>


<div id="toc_container">
<p class="toc_title">Sections:</p>
<ul class="toc_list">
<li><a href="#news">News</a></li>
<li><a href="#tutorials">Tutorials</a></li>
<li><a href="#materials">Materials</a></li>
</ul>
</div>


&nbsp; <br>
&nbsp; <br>
&nbsp; <br>


<h2 id="news">News</h2>

&nbsp; <br>


### Welcome on our course webpage!

This is the place where all the files needed for our tutorials will be linked. Additionally, here you will always find any important information regarding our classes.

The first thing to do is to get familiar with the 'Materials' section.

If you have any questions or encounter any problems, you can contact me via email through the icon at the bottom of the page (it is a Gmail address; the contact email will change when I obtain a university email)


&nbsp; <br>

### Project Information

The final deadline for your projects will be at the end of the semester, but it is advisable to get started as soon as possible. I will provide you with all the project details at a later date. For now, concentrate on choosing your project topic and locating a suitable dataset in `.csv` or `.xlsx` format, which is the most user-friendly option. Think about what genuinely interests you and what you can effectively present through data in the form of a brief article with at least two visualizations. Ensure your article addresses a specific problem or problems rather than merely presenting the dataset. Below, you'll find some sources for datasets that might assist you in finding a suitable one:


- <a href="https://www.kaggle.com/datasets">kaggle</a>         
- <a href="https://datasetsearch.research.google.com/">Google Dataset Search</a>        
- <a href="https://github.com/search?q=dataset+&type=repositories">Github</a> 
- <a href=" https://data.worldbank.org/">World Bank Open Data</a> 
- <a href="https://ec.europa.eu/eurostat/web/main/data/database">Eurostat</a>       
- Polish sources:      
- <a href="https://dane.gov.pl/pl">Otwarte Dane .gov</a>         
- <a href="https://stat.gov.pl/banki-i-bazy-danych/">GUS</a>           


&nbsp; <br>

### Project's Template

Through the link below, you can download the template for the project assignment, along with all of the requirements. The deadlines will be published here at a later time.

- <a href="https://github.com/Niklewa/Niklewa.github.io/raw/main/materials/projectsTemplate.zip">Project's template</a>

&nbsp; <br>

### Project's Deadlines

The link for submitting your projects will be on this website around one week prior to the deadline.

- First version deadline: 08.01.2024
- Final version deadline: 22.01.2024


&nbsp; <br>

<!--

### Project's Submission Link

Throughout this Google form, you can submit a folder with your project files. Please refer to the exact guidelines detailed in the project's template. I appreciate your commitment!    

- <a href="https://docs.google.com/forms/d/e/1FAIpQLSdGZFlcM8DKLHwwkolpCo5857JEyDurQeNvv3aFYQPx8ULkXQ/viewform?usp=sf_link">Sumbission Link</a>

-->

### Project's Feedback Info

Thank you all for sending me your first versions of your projects! I really appreciate your hard work, effort, and commitment that it took from you to learn that. For now, all the feedback has been sent. If you have not received it, check your spam folder first (of the email provided in the form). If you still have not received it, let me know.

Good luck in working on the final versions, can't wait to see it!

&nbsp; <br>
&nbsp; <br>

<h2 id="tutorials">Tutorials</h2>

&nbsp; <br>

In this section, there will be tutorial materials used in our classes.

- <a href="https://github.com/Niklewa/Niklewa.github.io/raw/main/materials/tut1TheBasics.zip">Tutorial 1, the basics</a>
- <a href="https://github.com/Niklewa/Niklewa.github.io/raw/main/materials/tut2CambridgeDataset.zip">Tutorial 2, Cambridge Dataset</a>
- <a href="https://github.com/Niklewa/Niklewa.github.io/raw/main/materials/tut3hateCrimes.zip">Tutorial 3, Hate Crimes</a>
- <a href="https://github.com/Niklewa/Niklewa.github.io/raw/main/materials/maps_vis.zip">Maps Tutorial</a>
- <a href="https://github.com/Niklewa/Niklewa.github.io/raw/main/materials/shootings_vis.zip">Shootings Tutorial</a>
- <a href="https://github.com/Niklewa/Niklewa.github.io/raw/main/materials/dashboardsTutorialStud.zip">Dashboards Tutorial</a>


&nbsp; <br>

### Presentations:

&nbsp; <br>


- <a href="https://github.com/Niklewa/Niklewa.github.io/raw/main/materials/presentations/whatIsDataAnalysisP1.pdf">What's data analysis? 09.10.2023</a>
- <a href="https://github.com/Niklewa/Niklewa.github.io/raw/main/materials/presentations/perceptionAndDataAnalysisP2.pdf">Perception and Data Visualization 16.10.2023</a>
- <a href="https://github.com/Niklewa/Niklewa.github.io/raw/main/materials/presentations/DataandVisualizationTypesP3.pdf">Data and Visualization types 23.10.2023</a>
- <a href="https://github.com/Niklewa/Niklewa.github.io/raw/main/materials/presentations/principlesOfDataVisualizationP4.pdf">6 Principles of Graphical Integrity 30.10.2023</a>
- <a href="https://github.com/Niklewa/Niklewa.github.io/raw/main/materials/presentations/deceptiveVisualsP5.pdf">Deceptive Visuals 13.11.2023</a>
- <a href="https://github.com/Niklewa/Niklewa.github.io/raw/main/materials/presentations/someStatisticalTrapsP6.pdf">Some Statistical Traps 20.11.2023</a>
- <a href="https://github.com/Niklewa/Niklewa.github.io/raw/main/materials/presentations/CorelationAndCausationP7.pdf">Correlation vs Causation 04.12.2023</a>





&nbsp; <br>
&nbsp; <br>

<h2 id="materials">Materials</h2>

&nbsp; <br>

In this section, I provide some introductory remarks and links to materials worth reading or watching. They are arranged in order from basic to more advanced levels. These materials cover mostly what you will learn in our classes, so they might be very helpful if you miss a tutorial or two.

&nbsp; <br>

### R installation

&nbsp; <br>

I strongly recommend installing R and RStudio on your personal computer and becoming familiar with them.

To set up the installation, follow this tutorial:

- <a href="https://www.youtube.com/watch?v=YrEe2TLr3MI">R installation tutorial</a>



&nbsp; <br>

### Basics of R 

&nbsp; <br>

To learn the very basics of using R and RStudio, which were covered in our first meeting, you can watch the following videos:

- <a href="https://www.youtube.com/watch?v=FIrsOBy5k58">Using R part 1</a>           
- <a href="https://www.youtube.com/watch?v=FY8BISK5DpM ">Using R part 2</a>


Additionally, you can follow a very useful R tutorial in the swirl package. You can find more information about swirl here:


-  <a href="https://swirlstats.com/students.html">How to use swirl</a>

I recommend starting with this part:

     1: R Programming: The basics of programming in R
     

Furthermore, if you really want to delve into R basics, I recommend reading the relevant chapter from Kruschke's book, "Doing Bayesian Data Analysis: 


- <a href="https://github.com/Niklewa/Niklewa.github.io/raw/main/materials/Ch3_Kruschke.pdf">download it here</a> (you can omit the following sections: 3.2.1; 3.7.5; 3.7.6; 3.8; 3.9)




&nbsp; <br>

### Additional materials

&nbsp; <br>

The following literature concerns creating visualizations, so it's important to understand some basics first. These materials cover, to a large extent, what we will do in our classes:



- <a href="https://r4ds.had.co.nz/data-visualisation.html">ggplot2 visualizations part 1</a>

- <a href="https://rkabacoff.github.io/datavis/">ggplot2 visualizations part 2</a>



Additionally, there is a theoretical side to data visualization, and you can find recommended literature about it in our syllabus.



&nbsp; <br>
&nbsp; <br>
&nbsp; <br>
&nbsp; <br>
&nbsp; <br>



<div class="footer">  
<center>

<p style="text-align:center;font-size:14px">Nikodem Lewandowski</p>  
&nbsp; &nbsp; <a href=mailto:"nikodemlewandowski@gmail.com/"><i class="fa fa-envelope" style="font-size:18px;color:grey"></i></a> &nbsp; &nbsp;
<a href="https://github.com/Niklewa"><i class="fa fa-github" style="font-size:18px;color:grey"></i></a> &nbsp; &nbsp;
<a href="https://www.linkedin.com/in/nikodem-lewandowski-96b482244/"><i class="fa fa-linkedin-square" style="font-size:18px;color:grey"></i></a> &nbsp; &nbsp;
<a href="https://www.facebook.com/nikodem.lewandowski.754"><i class="fa fa-facebook-f" style="font-size:18px;color:grey"></i></a> &nbsp; &nbsp;

 
</center>
</div>  















